// NOTE: This file is UNUSED. The actual Next.js app lives in ./client/ with its own next.config.ts.
// This was auto-generated by the Sentry wizard and is kept only to avoid breaking CI if referenced.
// Do NOT edit this file — configure Sentry in client/next.config.ts instead.

/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;
